media: src/assets
content:
  - name: blog
    label: Blog
    path: src/content/blog
    type: collection
    fields: 
      - name: title
        label: Title
        type: text
        required: true
      - name: description
        label: Description
        type: text
  - name: pages
    label: Site Pages
    path: src/content/*
    type: collection
    fields:
      - name: title
        label: Title
        type: text
        required: true
      - name: description
        label: Description
        type: text
      - name: image
        label: Image
        type: file
      - name: draft
        label: Draft
        type: boolean