components:
  button:
    label: Button
    type: object
    fields:
    - name: label
      label: Button text
      type: text
    - name: link
      label: Link
      type: text   
media: src/assets
content:
  - name: home
    label: Home
    path: src/content/home/-index.md
    type: file
    fields:
      - name: Fields
        component: sitepage
  - name: about
    label: About the game
    path: src/content/about/-index.md
    type: file
    fields:
      - name: Fields
        component: sitepage
  - name: about-us
    label: About us
    path: src/content/about_us/-index.md
    type: file
    fields:
      - name: Fields
        component: sitepage
  
  - name: blog
    label: Blog
    path: src/content/blog
    type: collection
    fields: 
      - name: title
        label: Title
        type: text
        required: true
      - name: description
        label: Description
        type: text
      - name: date
        label: Date
        type: date
      - name: body
        type: rich-text
        required: true

  - name: site-pages
    type: collection
    label: Site pages
    path: src/content
    subfolders: false
    fields:
    - name: title
      label: Title
      type: text
      required: true
    - name: description
      label: Description
      type: text
    - name: image
      label: Image
      type: file
    - name: imageAlt
      label: Image alt text
      type: text
    - name: draft
      label: Draft
      type: boolean
    - name: button
      component: button
    - name: body
      type: rich-text